/**:
  ros__parameters:
    framerate: 10.0
    io_method: "mmap"
    pixel_format: "mjpeg2rgb"
    image_width: 1280
    image_height: 720
    camera_info_url: "package://camera/config/camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1
