image_width: 1280
image_height: 720
camera_matrix:
  rows: 3
  cols: 3
  data: [750.052352, 0.000000, 647.851936, 0.000000, 749.703887, 298.896065, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.318372, 0.097881, -0.000662, -0.000256, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [564.108704, 0.000000, 648.736428, 0.000000, 0.000000, 682.043823, 286.985300, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

