navsat_transform_node:
  ros__parameters:
    base_link_frame: body
    gps_frame: gps_frame
    odom_frame: camera_init
    frequency: 20.0
    delay: 0.0
    sensor_timeout: 0.2
    use_odometry_yaw: true
    gps_topic: /fix
    odom_topic: /Odometry
    publish_filtered_gps: true
    filtered_gps_topic: /odometry/gps
    broadcast_cartesian_transform: false
    broadcast_utm_transform: false
    zero_altitude: true
    use_local_cartesian: false
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    wait_for_datum: false

ekf_global_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.2
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: true
    odom0: /Odometry
    odom0_queue_size: 5
    odom0_nodelay: true
    odom0_config: [
      true, true, false,
      false, false, true,
      true, true, false,
      false, false, true,
      false, false, false
    ]
    odom1: /odometry/gps
    odom1_queue_size: 5
    odom1_nodelay: true
    odom1_config: [
      true, true, false,
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, false
    ]
    odom1_differential: false
    odom1_relative: false
