/**:
  ros__parameters:
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 5.0
    odom_topic: /odometry/local

    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.5
      stateful: true

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: "Ackermann"
      AckermannConstraints:
        min_turning_r: 1.8
      model_dt: 0.2
      time_steps: 20
      batch_size: 300

      prune_distance: 1.7
      transform_tolerance: 0.2

      vx_max: 1.0
      vx_min: 0.0
      wz_max: 0.8

      critics:
        - ConstraintCritic
        - CostCritic
        - PathFollowCritic
        - GoalCritic

      CostCritic:
        enabled: true
        consider_footprint: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 5.0
      resolution: 0.05
      rolling_window: true
      width: 10
      height: 10

      footprint: "[[1.2, 0.75], [1.2, -0.75], [-1.2, -0.75], [-1.2, 0.75]]"

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: pointcloud
        pointcloud:
          topic: /livox/lidar_pc2
          data_type: PointCloud2
          marking: true
          clearing: true
          obstacle_range: 20.0
          raytrace_range: 25.0
          min_obstacle_height: 0.05
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 3.0

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    bond_timeout: 10.0
    node_names:
      - controller_server

